### ISSUE TITLE
Warning when building with clang-cl

### ISSUE THREAD

**Issue by Andoryuuta** [zyantific/zycore-c#16]
When building zydis with clang-cl on windows, it produces the following warning:
`clang-cl : warning : unknown argument ignored in clang-cl: '-std=c99' [-Wunknown-argument]`

This is because clang-cl expects a MSVC-like command line. I've tracked this down to the `zyan_set_common_flags` in zycore's CMakeLists.txt file [here](https://github.com/Andoryuuta/zycore-c/blob/ffcc3663200984e6cb54c2879f7b4de3f6112227/CMakeLists.txt#L72-L77), where it checks if `CMAKE_C_COMPILER_ID` is `Clang`.

I worked around this locally by also checking if the [semi-undocumented `CMAKE_CXX_SIMULATE_ID`](https://gitlab.kitware.com/cmake/cmake/issues/19724) is set to `MSVC`.

Replacing:
`"${CMAKE_C_COMPILER_ID}" STREQUAL "Clang" OR`
with:
`"${CMAKE_C_COMPILER_ID}" STREQUAL "Clang" AND (NOT "${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC") OR`

However, I'm not familiar enough with CMake to make full PR that I would trust to not break other things.

**Comment by athre0z** [comment]
Thanks for the report. I'll take a look.

On first glance it feels like it would have been smarter for CMake to just set `CMAKE_C_COMPILER_ID` to `MSVC` when Clang is invoked in MSVC emulation mode, but they will probably have had their reasons.

**Comment by athre0z** [comment]
Which version of CMake are you using, by the way?

**Comment by athre0z** [comment]
I switched the compiler detection to use the `MSVC` variable instead of `CMAKE_C_COMPILER_ID`. According to the documentation, this should also be set for other compilers pretending to be MSVC. I however noticed that this part mentioning compiler emulation was only added to the documentation in CMake 3.10, so you will have to make sure that you have a rathe recent version of CMake.

Since I don't really feel like setting up clang-cl I would appreciate it if you could check out [this branch](https://github.com/zyantific/zydis/tree/zycore-clang-cl-fix) and see if it resolves the issue.

**Comment by Andoryuuta** [comment]
I just tried it and that new branch works fine. 👍 

I'm using the CMake shipped via Visual Studio 2019's "C++ CMake tools for Windows" component which is `cmake version 3.15.19080502-MSVC_2`.

Thank you!

**Comment by athre0z** [comment]
Excellent -- I merged it into master!
